name: InventoryShare
version: '2.0-beta'
main: com.sugar_tree.inventoryshare.InventoryShare
website: https://github.com/the-sugar-tree/InventoryShare
api-version: 1.17
authors: [ sugar_tree ]
commands:
  inventoryshare:
    usage: /inventoryshare <inventory|advancement|AnnounceDeath|teaminventory|reload> [true|false]
    description: 콘피그 설정
    aliases:
      - is