name: InventoryShare
version: '1.1'
main: com.sugar_tree.inventoryshare.InventoryShare
api-version: 1.17
authors: [ sugar_tree ]
commands:
  inventoryshare:
    usage: /inventoryshare <advancement|DeathAnnounce|reload> [true|false]