name: InventoryShare
version: '1.2'
main: com.sugar_tree.inventoryshare.InventoryShare
website: https://github.com/the-sugar-tree/InventoryShare
api-version: 1.17
authors: [ sugar_tree ]
commands:
  inventoryshare:
    usage: /inventoryshare <advancement|DeathAnnounce|reload> [true|false]